'''Local operator-action workbook shell for a future Auto recovery hold.

This module creates one separate workbook beside the controller-written Live
status workbook.  It is deliberately local and dependency-free: the Lab-PC
desktop synchronization client may mirror the normal protocol-output folder,
but this module never accesses Google Drive, credentials, a network, the
original input workbook, a controller, or the robot.

Stage 11C1 creates the action-workbook shell exactly once for a run.  It does
not read an operator response or change any recovery, resource, or execution
behavior.  A later approved stage must validate an explicitly active request
before any response can be considered.
'''

import os

from auto_live_run_workbook import (
    AutoLiveRunWorkbookError,
    AutoLiveRunWorkbookRenderer
)


class AutoLiveRunOperatorActionWorkbookError(RuntimeError):
    '''Raised when the local operator-action workbook cannot be prepared.'''


class AutoLiveRunOperatorActionWorkbook:
    '''Creates the non-overwriting operator-action workbook shell.

    The workbook is intentionally distinct from ``<run>_LIVE.xlsx``.  The
    controller may regenerate the status workbook after every durable event,
    whereas this action workbook is created once and left untouched until a
    later hold-specific response reader is approved.
    '''

    ACTION_WORKBOOK_SUFFIX = '_OPERATOR_ACTIONS.xlsx'

    @staticmethod
    def _validate_nonempty_string(value, field_name):
        if not isinstance(value, str) or not value.strip():
            raise AutoLiveRunOperatorActionWorkbookError(
                '{} must be a nonempty string.'.format(field_name)
            )

    @staticmethod
    def _validate_nonnegative_integer(value, field_name):
        if isinstance(value, bool) or not isinstance(value, int) or value < 0:
            raise AutoLiveRunOperatorActionWorkbookError(
                '{} must be a nonnegative integer.'.format(field_name)
            )

    @classmethod
    def _workbook_path(cls, run_directory, run_display_name):
        cls._validate_nonempty_string(run_directory, 'run_directory')
        cls._validate_nonempty_string(run_display_name, 'run_display_name')
        live_run_directory = os.path.join(
            os.path.abspath(run_directory),
            AutoLiveRunWorkbookRenderer.LIVE_RUN_DIRECTORYNAME
        )
        workbook_name = '{}{}'.format(
            AutoLiveRunWorkbookRenderer._sanitize_filename_component(
                run_display_name
            ),
            cls.ACTION_WORKBOOK_SUFFIX
        )
        return live_run_directory, os.path.join(live_run_directory, workbook_name)

    @classmethod
    def _sheet_payloads(cls, run_id, initial_state_revision):
        return [
            (
                'Instructions',
                [
                    ['__TITLE__', 'Auto Operator Action Workbook'],
                    [
                        '__WARNING__',
                        'STAGE 11C1: THIS WORKBOOK IS NOT YET READ BY AUTO. '
                        'DO NOT EXPECT A RESPONSE ENTERED HERE TO CHANGE A RUN.'
                    ],
                    [
                        '__NOTE__',
                        'This file is separate from the controller-written '
                        'Live status workbook and from the original input '
                        'workbook. A future safe-hold stage will activate one '
                        'specific request before it reads a response.'
                    ],
                    ['__HEADER__', 'Rule', 'Meaning'],
                    [
                        'Status workbook',
                        'Do not edit <run>_LIVE.xlsx; it is regenerated by '
                        'the controller from durable local state.'
                    ],
                    [
                        'Original input workbook',
                        'Never changed by this action workflow.'
                    ],
                    [
                        'Future response scope',
                        'Only fields for one active, matching request will be '
                        'accepted after explicit validation.'
                    ],
                    [
                        'Offline fallback',
                        'The terminal remains the available recovery method '
                        'until action intake is separately implemented.'
                    ]
                ],
                [30, 112]
            ),
            (
                'Active Request',
                [
                    ['__TITLE__', 'Active Operator Request'],
                    [
                        '__NOTE__',
                        'No active request exists in Stage 11C1. This sheet '
                        'will be populated only by a future safe-hold stage.'
                    ],
                    ['__HEADER__', 'Field', 'Value'],
                    ['Request status', 'inactive'],
                    ['Run ID', run_id],
                    ['Initial state revision', initial_state_revision],
                    ['Request ID', 'not assigned'],
                    ['Expected state revision', 'not assigned'],
                    ['Blocking resource', 'not assigned'],
                    ['Allowed action', 'not assigned']
                ],
                [30, 96]
            ),
            (
                'Operator Response',
                [
                    ['__TITLE__', 'Operator Response'],
                    [
                        '__WARNING__',
                        'INACTIVE IN STAGE 11C1. VALUES BELOW ARE NOT READ OR '
                        'ACTED UPON BY AUTO.'
                    ],
                    [
                        '__NOTE__',
                        'A future hold-specific reader will accept only a '
                        'response whose run ID, request ID, and expected state '
                        'revision match the active request.'
                    ],
                    ['__HEADER__', 'Field', 'Value'],
                    ['Run ID', run_id],
                    ['Request ID', ''],
                    ['Expected state revision', ''],
                    ['Requested action', ''],
                    ['Operator response', ''],
                    ['Replacement details', ''],
                    ['Operator note', '']
                ],
                [30, 96]
            )
        ]

    @classmethod
    def initialize(
        cls,
        run_directory,
        run_display_name,
        run_id,
        initial_state_revision
    ):
        '''Creates one action workbook shell without overwriting it.

        A second initialization call returns the already-existing path without
        reading, validating, or changing the file. This prevents future
        controller status refreshes from overwriting an operator's local or
        desktop-synchronized edits.
        '''
        cls._validate_nonempty_string(run_id, 'run_id')
        cls._validate_nonnegative_integer(
            initial_state_revision,
            'initial_state_revision'
        )
        live_run_directory, workbook_path = cls._workbook_path(
            run_directory,
            run_display_name
        )
        try:
            if not os.path.isdir(live_run_directory):
                os.makedirs(live_run_directory)
        except OSError as exc:
            raise AutoLiveRunOperatorActionWorkbookError(
                'Could not create Live_Run directory {}: {}.'.format(
                    live_run_directory,
                    exc
                )
            )

        if os.path.exists(workbook_path):
            if not os.path.isfile(workbook_path):
                raise AutoLiveRunOperatorActionWorkbookError(
                    'Operator-action workbook path is not a file: {}.'.format(
                        workbook_path
                    )
                )
            return {
                'workbook_path': workbook_path,
                'created': False,
                'run_id': run_id,
                'initial_state_revision': initial_state_revision
            }

        try:
            AutoLiveRunWorkbookRenderer.write_local_workbook(
                workbook_path,
                cls._sheet_payloads(run_id, initial_state_revision)
            )
        except AutoLiveRunWorkbookError as exc:
            raise AutoLiveRunOperatorActionWorkbookError(
                'Could not create operator-action workbook: {}.'.format(exc)
            )

        return {
            'workbook_path': workbook_path,
            'created': True,
            'run_id': run_id,
            'initial_state_revision': initial_state_revision
        }
